# Generated by Django 4.2.1 on 2023-05-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='surname',
            field=models.CharField(default='new', max_length=30),
        ),
    ]
