# Generated by Django 4.2.1 on 2023-05-20 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230520_0418'),
    ]

    operations = [
    ]
